### ISSUE TITLE
Model conversion error

### ISSUE THREAD

**Issue by masinov** [7eu7d7/HCP-Diffusion#23]
Model conversion from webui to diffusers framework wont work with diffusers==0.18.x
Trying to do so will yield the following error:
"TypeError: convert_ldm_clip_checkpoint() got an unexpected keyword argument 'text_encoder'"
Downgrading to diffusers==0.17.1 fixes this issue.
Perhaps the requirements should be modified to enforce the use of 0.17.x diffusers lib.

**Comment by 7eu7d7** [comment]
New version fix this bug and support to ```diffusers==0.18```
